CODE="it"
L=dict(name="Italiano", flag="🇮🇹",
tagline="Il sostituto di CapCut davvero gratuito, open source e multipiattaforma.",
note="Tradotto dal README inglese il 2 ottobre 2026. La versione inglese è quella tenuta aggiornata.",
sponsors_h="Sponsor paganti", proxyon="Proxy a consumo per sviluppatori", proxyon_code="Usa il codice <code>JUB0T</code> per il 20 % di sconto",
logo_here="Il tuo logo qui", sponsor_link="Sponsorizza Concat", slot="e il tuo nome, il tuo logo e il tuo link prendono questo posto",
about_h="Informazioni",
about1="Concat è un editor video gratuito e open source, un’alternativa a CapCut per macOS, Windows, Linux e Android. Copre ciò per cui la gente apre davvero CapCut: sottotitoli automatici, sintesi vocale, rimozione dello sfondo, animazione con fotogrammi chiave, effetti e titoli, montaggio multitraccia, esportazione 4K. Senza nessuna fregatura: niente filigrana, niente account, niente abbonamento, niente caricamenti.",
about2="Tutto gira in locale su un motore nativo in Rust con un compositore su GPU. Installalo, trascina il girato, taglia. I modelli di IA per sottotitoli, voci e scontorno si scaricano una volta dalle Impostazioni e poi funzionano offline. Il tuo girato non lascia mai il tuo disco.",
good_for="Adatto a:", good_for_list="TikTok, Reels e Shorts, video YouTube, tutorial e registrazioni dello schermo, clip di podcast, meme.",
machines="Anche per le macchine:", machines_text="un’API JSON-RPC, gRPC e MCP, così anche script e agenti IA possono montare video con lui.",
highlights_h="In evidenza",
highlights=[
"🚫 **Niente filigrane. Niente account. Niente paywall.** Mai.",
"🔒 **100 % locale.** Niente viene caricato. Funziona offline.",
"💬 **Sottotitoli automatici.** Whisper in locale. Scegli la dimensione del modello e ottieni sottotitoli stilizzati sulla timeline.",
"🗣️ **Sintesi vocale + clonazione della voce.** Voci locali gratuite, o qualsiasi voce da pochi secondi di registrazione.",
"🧍 **Rimozione dello sfondo.** Persone, oggetti, o dipingi la maschera tu stesso.",
"🎞️ **Fotogrammi chiave.** Posizione, scala, rotazione, opacità, volume, parametri degli effetti. Editor di curve integrato.",
"✨ **Oltre 170 effetti, filtri, transizioni e animazioni di testo.** Resi dalla GPU, dal vivo nell’anteprima.",
"✂️ **Taglia in fretta.** Dividi, rifila, ripple, unisci, fermo immagine, velocità. Timeline magnetica se la vuoi.",
"🎚️ **Multitraccia, multi-timeline.** Più montaggi in un progetto. Metodi di fusione, ritaglio, ribaltamenti.",
"📝 **Titoli.** Font, contorno, ombra, placca di sfondo. Preset da cui partire.",
"🎙️ **Pulizia della voce con un interruttore.** Riduci il rumore, migliora la voce, livella il volume. Più scoiattolo, robot, telefono e compagnia.",
"📤 **Esportazione.** H.264, HEVC, AV1. Fino a 4K 60, colore a 10 bit.",
"🦀 **Motore nativo in Rust.** Compositore su GPU, proxy, decodifica hardware. Il 4K scorre fluido.",
"🤖 **Scriptabile.** API JSON-RPC, gRPC e MCP, più una CLI. Gli agenti IA possono montare video con lui.",
"🖥️ **macOS, Windows, Linux, Android.** 14 lingue. Stessa app, stessi file di progetto.",
],
download_h="Download", two_ways="Due strade:",
website="Il sito web", website_text="ti dà la build giusta per la tua macchina. Parti da qui.",
releases_text="ha ogni build per ogni piattaforma, con installer, pacchetti e checksum. Per quando vuoi scegliere.",
beta="Concat è in **beta**: funziona, e ha ancora qualche spigolo. [Segnalalo](https://github.com/jub0t/Concat/issues) quando ne trovi uno.",
platforms="Piattaforme",
win="x86_64 e ARM. Un setup e un `.msi`. Se SmartScreen blocca una build non firmata: **Ulteriori informazioni** › **Esegui comunque**",
mac="Intel e Apple Silicon. Se macOS si rifiuta di aprire una build non firmata: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 e ARM. `.deb`, `.rpm`, `.AppImage` e un pacchetto Arch. Anche un Flatpak su **[Flatpark](https://flatpark.org/apps/app.concat.editor/)**, un remote Flatpak della community che impacchetta il `.deb` x86_64 di ogni versione e si aggiorna con essa",
android="telefoni e tablet", ios="iPhone e iPad, con sideload",
legend="✅ Supportato · 🚧 In lavorazione · 🧪 Da testare",
sysreq="I **requisiti di sistema** e le dimensioni dei modelli opzionali sono sul [sito web](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Per iniziare", start1="Scaricalo, aprilo, trascina il girato, taglia. Niente account, niente configurazione.",
reporting="Per segnalare qualcosa:", reporting_text="ogni avvio scrive un log, e in Impostazioni › Informazioni c’è il pulsante che lo apre accanto a quello che copia le informazioni di sistema. Allega entrambi a una [issue](https://github.com/jub0t/Concat/issues) e la segnalazione arriva con tutto il necessario. Gli ultimi dieci avvii vengono conservati, quindi quello di ieri c’è ancora; niente viene mai inviato da nessuna parte da solo.",
contribute_h="Come contribuire",
contrib1="Il modo migliore per contribuire è prendere una build dalla pagina [Releases](https://github.com/jub0t/Concat/releases) e usarla: trova dove si rompe, e di’ dove potrebbe essere migliore.",
contrib2="Pronto a scrivere codice? [CONTRIBUTING.md](../CONTRIBUTING.md) copre la configurazione, la struttura dell’albero, i controlli da eseguire e come vengono licenziati i contributi. Guidi Concat da uno script, un servizio o un agente? [La documentazione per sviluppatori](https://concatenate.pages.dev/docs) copre l’API di Concat e i suoi trasporti: JSON-RPC, gRPC e MCP. [Questa Discussion](https://github.com/jub0t/Concat/discussions/3) è dove il progetto è stato annunciato.",
contrib3="I contributori possono chiedere un ruolo `@Contributor` sul server Discord, basta chiederlo.",
contributors_h="Contributori", stars_h="Storico delle stelle",
sponsoring_h="Sponsorizzazione",
sponsoring1="Concat non ha un paywall e non lo avrà mai: niente filigrana, niente account, niente piano a pagamento. La sponsorizzazione è ciò che ne fa le veci. Se Concat ha preso il posto di un abbonamento per te, una frazione di quello lo tiene in vita.",
where_h="Dove va", where_text="La [roadmap](https://concatenate.pages.dev/roadmap) spiega cosa paga la sponsorizzazione, e quanto costa ogni pezzo.",
payment_text='Scegli un livello sul [sito web](https://concatenate.pages.dev/#sponsor).',
closing="Non sei in condizione di contribuire? Anche una stella, una segnalazione di bug o una parola a qualcuno che monta video contano molto.",
)
