CODE="pt-BR"
L=dict(name="Português (Brasil)", flag="🇧🇷",
tagline="O substituto do CapCut realmente gratuito, de código aberto e multiplataforma.",
note="Traduzido do README em inglês em 2 de outubro de 2026. A versão em inglês é a que se mantém atualizada.",
sponsors_h="Patrocinadores pagos", proxyon="Proxies pagos por uso para desenvolvedores", proxyon_code="Use o código <code>JUB0T</code> para 20 % de desconto",
logo_here="Seu logo aqui", sponsor_link="Patrocine o Concat", slot="e seu nome, seu logo e seu link ocupam este espaço",
about_h="Sobre",
about1="O Concat é um editor de vídeo gratuito e de código aberto, uma alternativa ao CapCut para macOS, Windows, Linux e Android. Ele cobre o que as pessoas realmente abrem o CapCut para fazer: legendas automáticas, texto para fala, remoção de fundo, animação por keyframes, efeitos e títulos, corte multipista, exportação em 4K. Sem nenhuma pegadinha: sem marca d’água, sem conta, sem assinatura, sem upload.",
about2="Tudo roda localmente em um motor nativo em Rust com um compositor na GPU. Instale, solte o material, corte. Os modelos de IA para legendas, vozes e recorte são baixados uma vez nas Configurações e depois funcionam offline. Seu material nunca sai do seu disco.",
good_for="Bom para:", good_for_list="TikTok, Reels e Shorts, vídeos do YouTube, tutoriais e gravações de tela, trechos de podcast, memes.",
machines="Também para máquinas:", machines_text="uma API JSON-RPC, gRPC e MCP, para que scripts e agentes de IA também possam cortar vídeo com ele.",
highlights_h="Destaques",
highlights=[
"🚫 **Sem marca d’água. Sem conta. Sem paywall.** Nunca.",
"🔒 **100 % local.** Nada é enviado. Funciona offline.",
"💬 **Legendas automáticas.** Whisper local. Escolha o tamanho do modelo e receba legendas estilizadas na linha do tempo.",
"🗣️ **Texto para fala + clonagem de voz.** Vozes locais gratuitas, ou qualquer voz a partir de alguns segundos de gravação.",
"🧍 **Remoção de fundo.** Pessoas, objetos, ou pinte a máscara você mesmo.",
"🎞️ **Keyframes.** Posição, escala, rotação, opacidade, volume, parâmetros de efeitos. Editor de curvas embutido.",
"✨ **Mais de 170 efeitos, filtros, transições e animações de texto.** Renderizados na GPU, ao vivo na prévia.",
"✂️ **Corte rápido.** Dividir, aparar, ripple, mesclar, congelar quadro, velocidade. Linha do tempo magnética se você quiser.",
"🎚️ **Multipista, múltiplas linhas do tempo.** Vários cortes em um projeto. Modos de mesclagem, corte, inversões.",
"📝 **Títulos.** Fontes, contorno, sombra, placa de fundo. Predefinições para começar.",
"🎙️ **Limpeza de voz com um interruptor.** Reduzir ruído, realçar a voz, nivelar o volume. Mais esquilo, robô, telefone e companhia.",
"📤 **Exportação.** H.264, HEVC, AV1. Até 4K 60, cor de 10 bits.",
"🦀 **Motor nativo em Rust.** Compositor na GPU, proxies, decodificação por hardware. O 4K navega suavemente.",
"🤖 **Automatizável.** API JSON-RPC, gRPC e MCP, mais uma CLI. Agentes de IA podem cortar vídeo com ele.",
"🖥️ **macOS, Windows, Linux, Android.** 14 idiomas. O mesmo app, os mesmos arquivos de projeto.",
],
download_h="Download", two_ways="Dois caminhos:",
website="O site", website_text="entrega a build certa para a sua máquina. Comece por aqui.",
releases_text="tem todas as builds para todas as plataformas, com instaladores, pacotes e checksums. Para quando você quiser escolher.",
beta="O Concat está em **beta**: funciona, e ainda tem arestas. [Conte](https://github.com/jub0t/Concat/issues) quando encontrar uma.",
platforms="Plataformas",
win="x86_64 e ARM. Um instalador e um `.msi`. Se o SmartScreen barrar uma build sem assinatura: **Mais informações** › **Executar assim mesmo**",
mac="Intel e Apple Silicon. Se o macOS se recusar a abrir uma build sem assinatura: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 e ARM. `.deb`, `.rpm`, `.AppImage` e um pacote para Arch. Também um Flatpak no **[Flatpark](https://flatpark.org/apps/app.concat.editor/)**, um remoto Flatpak da comunidade que empacota o `.deb` x86_64 de cada versão e se atualiza com ela",
android="celulares e tablets", ios="iPhone e iPad, por sideload",
legend="✅ Suportado · 🚧 Em andamento · 🧪 A testar",
sysreq="Os **requisitos do sistema** e os tamanhos dos modelos opcionais estão no [site](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Primeiros passos", start1="Baixe, abra, solte o material, corte. Sem conta, sem configuração.",
reporting="Para relatar algo:", reporting_text="cada execução grava um log, e em Configurações › Sobre está o botão que o abre, ao lado do que copia as informações do seu sistema. Anexe os dois a uma [issue](https://github.com/jub0t/Concat/issues) e o relato chega com tudo o que precisa. As últimas dez execuções são guardadas, então a de ontem ainda está lá; nada é enviado a lugar nenhum por conta própria.",
contribute_h="Como contribuir",
contrib1="A melhor forma de contribuir é pegar uma build na página de [Releases](https://github.com/jub0t/Concat/releases) e usá-la: descubra onde ela quebra e diga onde poderia ser melhor.",
contrib2="Pronto para escrever código? O [CONTRIBUTING.md](../CONTRIBUTING.md) cobre a configuração, a organização da árvore, as verificações a rodar e como as contribuições são licenciadas. Controla o Concat a partir de um script, um serviço ou um agente? [A documentação para desenvolvedores](https://concatenate.pages.dev/docs) cobre a API do Concat e seus transportes: JSON-RPC, gRPC e MCP. [Esta Discussion](https://github.com/jub0t/Concat/discussions/3) é onde o projeto foi anunciado.",
contrib3="Contribuidores podem pedir o papel `@Contributor` no servidor do Discord, basta pedir.",
contributors_h="Contribuidores", stars_h="Histórico de estrelas",
sponsoring_h="Patrocínio",
sponsoring1="O Concat não tem paywall e nunca terá: sem marca d’água, sem conta, sem plano pago. O patrocínio é o que fica no lugar disso. Se o Concat substituiu uma assinatura para você, uma fração dela o mantém funcionando.",
where_h="Para onde vai", where_text="O [roadmap](https://concatenate.pages.dev/roadmap) mostra o que o patrocínio paga, e quanto custa cada parte.",
payment_text='Escolha um nível no [site](https://concatenate.pages.dev/#sponsor).',
closing="Não pode contribuir agora? Uma estrela, um relato de bug ou uma palavra para alguém que edita vídeo também valem muito.",
)
