CODE="hr"
L=dict(name="Hrvatski", flag="🇭🇷",
tagline="Istinski besplatna zamjena za CapCut otvorenog koda, za sve platforme.",
note="Prevedeno s engleskog README-a 2. listopada 2026. Engleska je verzija ona koja se održava ažurnom.",
sponsors_h="Plaćeni sponzori", proxyon="Proxyji s plaćanjem po potrošnji za razvojne programere", proxyon_code="Kod <code>JUB0T</code> daje 20 % popusta",
logo_here="Vaš logo ovdje", sponsor_link="Sponzorirajte Concat", slot="i vaše ime, logo i poveznica zauzimaju ovo mjesto",
about_h="O projektu",
about1="Concat je besplatan videouređivač otvorenog koda i alternativa CapCutu za macOS, Windows, Linux i Android. Pokriva ono zbog čega ljudi zapravo otvaraju CapCut: automatske titlove, pretvorbu teksta u govor, uklanjanje pozadine, animaciju ključnim kadrovima, efekte i naslove, višetračno rezanje, izvoz u 4K. Bez ikakvih kvaka: bez vodenog žiga, bez računa, bez pretplate, bez učitavanja.",
about2="Sve se izvodi lokalno na nativnom Rust motoru s GPU kompozitorom. Instalirajte, ubacite snimke, režite. AI modeli za titlove, glasove i izrezivanje preuzimaju se jednom iz Postavki i nakon toga rade izvan mreže. Vaše snimke nikada ne napuštaju vaš disk.",
good_for="Dobro za:", good_for_list="TikTok, Reels i Shorts, YouTube videe, tutorijale i snimke zaslona, isječke podcasta, memeove.",
machines="I za strojeve:", machines_text="JSON-RPC, gRPC i MCP API, pa skripte i AI agenti također mogu njime rezati video.",
highlights_h="Istaknuto",
highlights=[
"🚫 **Bez vodenih žigova. Bez računa. Bez naplate.** Nikad.",
"🔒 **100 % lokalno.** Ništa se ne učitava. Radi izvan mreže.",
"💬 **Automatski titlovi.** Lokalni Whisper. Odaberite veličinu modela i dobijete stilizirane titlove na vremenskoj crti.",
"🗣️ **Tekst u govor + kloniranje glasa.** Besplatni lokalni glasovi ili bilo koji glas iz nekoliko sekundi snimke.",
"🧍 **Uklanjanje pozadine.** Osobe, predmeti ili sami nacrtajte masku.",
"🎞️ **Ključni kadrovi.** Položaj, skala, rotacija, prozirnost, glasnoća, parametri efekata. Ugrađeni uređivač krivulja.",
"✨ **Više od 170 efekata, filtara, prijelaza i animacija teksta.** Iscrtano na GPU-u, uživo u pregledu.",
"✂️ **Brzo rezanje.** Podijeli, skrati, ripple, spoji, zamrzni kadar, brzina. Magnetska vremenska crta ako je želite.",
"🎚️ **Više traka, više vremenskih crta.** Više montaža u jednom projektu. Načini stapanja, obrezivanje, zrcaljenja.",
"📝 **Naslovi.** Fontovi, obrub, sjena, pozadinska pločica. Predlošci za početak.",
"🎙️ **Čišćenje glasa jednim prekidačem.** Uklanjanje šuma, poboljšanje glasa, izjednačavanje glasnoće. Plus vjeverica, robot, telefon i društvo.",
"📤 **Izvoz.** H.264, HEVC, AV1. Do 4K 60, 10-bitna boja.",
"🦀 **Nativni Rust motor.** GPU kompozitor, proxyji, hardversko dekodiranje. 4K se pregledava glatko.",
"🤖 **Skriptabilan.** JSON-RPC, gRPC i MCP API, plus CLI. AI agenti mogu njime rezati video.",
"🖥️ **macOS, Windows, Linux, Android.** 14 jezika. Ista aplikacija, iste datoteke projekta.",
],
download_h="Preuzimanje", two_ways="Dva ulaza:",
website="Web-stranica", website_text="daje vam pravu inačicu za vaše računalo. Počnite ovdje.",
releases_text="ima svaku inačicu za svaku platformu, s instalacijama, paketima i kontrolnim zbrojevima. Za kad želite birati.",
beta="Concat je u **beti**: radi, a još ima rubova. [Javite](https://github.com/jub0t/Concat/issues) kad naiđete na jedan.",
platforms="Platforme",
win="x86_64 i ARM. Instalacija i `.msi`. Ako SmartScreen zaustavi nepotpisanu inačicu: **Više informacija** › **Svejedno pokreni**",
mac="Intel i Apple Silicon. Ako macOS odbije otvoriti nepotpisanu inačicu: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 i ARM. `.deb`, `.rpm`, `.AppImage` i Arch paket. Također Flatpak na **[Flatparku](https://flatpark.org/apps/app.concat.editor/)**, Flatpak repozitoriju zajednice koji omata x86_64 `.deb` svakog izdanja i ažurira se s njim",
android="telefoni i tableti", ios="iPhone i iPad, sideloadom",
legend="✅ Podržano · 🚧 U izradi · 🧪 Za testiranje",
sysreq="**Zahtjevi sustava** i veličine neobaveznih modela nalaze se na [web-stranici](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Prvi koraci", start1="Preuzmite, otvorite, ubacite snimke, režite. Bez računa, bez postavljanja.",
reporting="Ako nešto prijavljujete:", reporting_text="svako pokretanje zapisuje dnevnik, a u Postavke › O programu nalazi se gumb koji ga otvara, uz onaj koji kopira podatke o vašem sustavu. Priložite oboje uz [issue](https://github.com/jub0t/Concat/issues) i prijava stiže sa svime što joj treba. Čuva se zadnjih deset pokretanja, pa je i jučerašnje još tu; ništa se nikada ne šalje nikamo samo od sebe.",
contribute_h="Kako doprinijeti",
contrib1="Najbolji način doprinosa jest uzeti inačicu sa stranice [Releases](https://github.com/jub0t/Concat/releases) i koristiti je: pronaći gdje puca i reći gdje bi mogla biti bolja.",
contrib2="Spremni pisati kod? [CONTRIBUTING.md](../CONTRIBUTING.md) pokriva postavljanje, raspored stabla, provjere koje treba pokrenuti i kako se doprinosi licenciraju. Upravljate Concatom iz skripte, servisa ili agenta? [Dokumentacija za razvojne programere](https://concatenate.pages.dev/docs) pokriva Concat API i njegove prijenose: JSON-RPC, gRPC i MCP. [U ovoj raspravi](https://github.com/jub0t/Concat/discussions/3) projekt je najavljen.",
contrib3="Suradnici mogu zatražiti ulogu `@Contributor` na Discord poslužitelju, samo pitajte.",
contributors_h="Suradnici", stars_h="Povijest zvjezdica",
sponsoring_h="Sponzoriranje",
sponsoring1="Concat nema naplatu i nikada je neće imati: bez vodenog žiga, bez računa, bez plaćene razine. Sponzoriranje stoji umjesto toga. Ako je Concat za vas zamijenio pretplatu, djelić nje održava ga na životu.",
where_h="Kamo odlazi", where_text="[Plan razvoja](https://concatenate.pages.dev/roadmap) prikazuje što sponzorstvo plaća i koliko koja stavka stoji.",
payment_text='Odaberite razinu na [web-stranici](https://concatenate.pages.dev/#sponsor).',
closing="Niste u mogućnosti pridonijeti? Zvjezdica, prijava greške ili riječ nekome tko montira video također puno znače.",
)
