CODE="zh-TW"
L=dict(name="繁體中文", flag="🇹🇼",
tagline="真正免費、開源、跨平台的 CapCut 替代方案。",
note="譯自 2026 年 10 月 2 日的英文 README。以英文版為準，它才是持續更新的版本。",
sponsors_h="付費贊助商", proxyon="給開發者的按量計費代理", proxyon_code="使用代碼 <code>JUB0T</code> 享 20 % 折扣",
logo_here="您的 Logo 放這裡", sponsor_link="贊助 Concat", slot="您的名字、Logo 與連結就會出現在這個位置",
about_h="關於",
about1="Concat 是一款免費、開源的影片編輯器，是 macOS、Windows、Linux 與 Android 上的 CapCut 替代方案。它涵蓋了人們真正打開 CapCut 要做的事：自動字幕、文字轉語音、背景移除、關鍵影格動畫、特效與標題、多軌剪輯、4K 輸出。而且沒有任何陷阱：無浮水印、不需帳號、不需訂閱、不上傳。",
about2="一切都在本機執行，基於帶 GPU 合成器的原生 Rust 引擎。安裝、拖入素材、開剪。字幕、語音與去背所用的 AI 模型只需在設定中下載一次，之後離線可用。您的素材永遠不會離開您的硬碟。",
good_for="適合：", good_for_list="TikTok、Reels 與 Shorts，YouTube 影片，教學與螢幕錄影，Podcast 片段，迷因。",
machines="也適合機器：", machines_text="提供 JSON-RPC、gRPC 與 MCP API，指令碼與 AI 代理同樣可以用它剪影片。",
highlights_h="亮點",
highlights=[
"🚫 **無浮水印。無帳號。無付費牆。** 永遠如此。",
"🔒 **100 % 本機。** 不上傳任何內容。離線可用。",
"💬 **自動字幕。** 本機 Whisper。選一個模型大小，帶樣式的字幕就排進時間軸。",
"🗣️ **文字轉語音 + 聲音複製。** 免費的本機聲音，或用幾秒鐘錄音複製任何聲音。",
"🧍 **背景移除。** 人物、物體，或者自己塗抹遮罩。",
"🎞️ **關鍵影格。** 位置、縮放、旋轉、不透明度、音量、特效參數。內建曲線編輯器。",
"✨ **170 多種特效、濾鏡、轉場與文字動畫。** GPU 算繪，預覽中即時呈現。",
"✂️ **快剪。** 分割、修剪、漣漪、合併、定格、變速。想要的話還有磁性時間軸。",
"🎚️ **多軌、多時間軸。** 一個專案裡放多個剪輯版本。混合模式、裁切、翻轉。",
"📝 **標題。** 字型、描邊、陰影、背景底板。有預設可作起點。",
"🎙️ **一鍵人聲淨化。** 降噪、增強人聲、響度均衡。還有花栗鼠、機器人、電話等效果。",
"📤 **輸出。** H.264、HEVC、AV1。最高 4K 60，10 位元色彩。",
"🦀 **原生 Rust 引擎。** GPU 合成器、代理、硬體解碼。4K 拖曳也順暢。",
"🤖 **可指令碼化。** JSON-RPC、gRPC 與 MCP API，外加 CLI。AI 代理可以用它剪影片。",
"🖥️ **macOS、Windows、Linux、Android。** 14 種語言。同一個應用程式，同樣的專案檔。",
],
download_h="下載", two_ways="兩個入口：",
website="官網", website_text="會給您適合您機器的版本。從這裡開始。",
releases_text="有每個平台的每個版本，附帶安裝程式、套件與校驗和。想自己挑選時用它。",
beta="Concat 處於 **測試版**：能用，但還有毛邊。遇到了請 [告訴我們](https://github.com/jub0t/Concat/issues)。",
platforms="平台",
win="x86_64 與 ARM。安裝程式與 `.msi`。如果 SmartScreen 攔截未簽署版本：**其他資訊** › **仍要執行**",
mac="Intel 與 Apple 晶片。如果 macOS 拒絕開啟未簽署版本：`xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 與 ARM。`.deb`、`.rpm`、`.AppImage` 與 Arch 套件。另有 **[Flatpark](https://flatpark.org/apps/app.concat.editor/)** 上的 Flatpak，這是一個社群 Flatpak 儲存庫，封裝每個版本的 x86_64 `.deb` 並隨之更新",
android="手機與平板", ios="iPhone 與 iPad，需側載",
legend="✅ 已支援 · 🚧 開發中 · 🧪 待測試",
sysreq="**系統需求** 與可選模型的大小見 [官網](https://concatenate.pages.dev/guides/system-requirements)。",
start_h="開始使用", start1="下載、開啟、拖入素材、開剪。不需帳號，不需設定。",
reporting="回報問題：", reporting_text="每次執行都會寫日誌，設定 › 關於 裡有開啟日誌的按鈕，旁邊是複製系統資訊的按鈕。把兩者附到一個 [issue](https://github.com/jub0t/Concat/issues) 裡，回報就帶齊了所需的一切。保留最近十次執行，所以昨天的還在；任何內容都不會自動送到任何地方。",
contribute_h="如何貢獻",
contrib1="最好的貢獻方式是從 [Releases](https://github.com/jub0t/Concat/releases) 頁面拿一個版本來用：找到它哪裡會壞，說出它哪裡可以更好。",
contrib2="準備寫程式了？[CONTRIBUTING.md](../CONTRIBUTING.md) 介紹了環境建置、目錄結構、要執行的檢查以及貢獻的授權方式。要從指令碼、服務或代理驅動 Concat？[開發者文件](https://concatenate.pages.dev/docs) 介紹了 Concat API 及其傳輸方式：JSON-RPC、gRPC 與 MCP。專案在 [這個 Discussion](https://github.com/jub0t/Concat/discussions/3) 中發布。",
contrib3="貢獻者可以在 Discord 伺服器申請 `@Contributor` 身分組，開口要就行。",
contributors_h="貢獻者", stars_h="Star 歷史",
sponsoring_h="贊助",
sponsoring1="Concat 沒有付費牆，以後也不會有：無浮水印、無帳號、無付費方案。贊助就是替代它的方式。如果 Concat 替您省下了一份訂閱，拿出其中一小部分就能讓它繼續走下去。",
where_h="錢用在哪", where_text="[路線圖](https://concatenate.pages.dev/roadmap) 列出了贊助用於哪些事，以及每一項的花費。",
payment_text='在 [官網](https://concatenate.pages.dev/#sponsor) 選一個方案。',
closing="暫時不方便出力？一個 Star、一份 bug 回報，或者向剪影片的朋友提一句，同樣意義重大。",
)
