CODE="fr"
L=dict(name="Français", flag="🇫🇷",
tagline="Le remplaçant de CapCut vraiment gratuit, open source et multiplateforme.",
note="Traduit du README anglais le 2 octobre 2026. La version anglaise est celle qui est tenue à jour.",
sponsors_h="Sponsors payants", proxyon="Proxys à l’usage pour les développeurs", proxyon_code="Code <code>JUB0T</code> pour 20 % de réduction",
logo_here="Votre logo ici", sponsor_link="Sponsorisez Concat", slot="et votre nom, votre logo et votre lien prennent cette place",
about_h="À propos",
about1="Concat est un éditeur vidéo gratuit et open source, une alternative à CapCut pour macOS, Windows, Linux et Android. Il couvre ce pour quoi on ouvre vraiment CapCut : sous-titres automatiques, synthèse vocale, suppression d’arrière-plan, animation par images clés, effets et titres, montage multipiste, export 4K. Sans aucun piège : pas de filigrane, pas de compte, pas d’abonnement, pas d’envoi.",
about2="Tout tourne en local sur un moteur natif en Rust avec un compositeur GPU. Installez, déposez vos rushes, montez. Les modèles d’IA pour les sous-titres, les voix et le détourage se téléchargent une fois depuis les Réglages et fonctionnent ensuite hors ligne. Vos rushes ne quittent jamais votre disque.",
good_for="Idéal pour :", good_for_list="TikTok, Reels et Shorts, vidéos YouTube, tutoriels et captures d’écran, extraits de podcast, mèmes.",
machines="Aussi pour les machines :", machines_text="une API JSON-RPC, gRPC et MCP, pour que les scripts et les agents IA puissent eux aussi monter de la vidéo avec.",
highlights_h="Points forts",
highlights=[
"🚫 **Pas de filigrane. Pas de compte. Pas de paywall.** Jamais.",
"🔒 **100 % local.** Rien n’est envoyé. Fonctionne hors ligne.",
"💬 **Sous-titres automatiques.** Whisper en local. Choisissez une taille de modèle, obtenez des sous-titres stylés sur la timeline.",
"🗣️ **Synthèse vocale + clonage de voix.** Voix locales gratuites, ou n’importe quelle voix à partir de quelques secondes d’enregistrement.",
"🧍 **Suppression d’arrière-plan.** Personnes, objets, ou peignez le masque vous-même.",
"🎞️ **Images clés.** Position, échelle, rotation, opacité, volume, paramètres d’effets. Éditeur de courbes intégré.",
"✨ **Plus de 170 effets, filtres, transitions et animations de texte.** Rendus par le GPU, en direct dans l’aperçu.",
"✂️ **Montez vite.** Couper, rogner, ripple, fusionner, arrêt sur image, vitesse. Timeline magnétique si vous la voulez.",
"🎚️ **Multipiste, multi-timeline.** Plusieurs montages dans un projet. Modes de fusion, recadrage, retournements.",
"📝 **Titres.** Polices, contour, ombre, plaque de fond. Des préréglages pour démarrer.",
"🎙️ **Nettoyage de voix d’un seul geste.** Débruiter, rehausser la voix, niveler le volume. Plus écureuil, robot, téléphone et compagnie.",
"📤 **Export.** H.264, HEVC, AV1. Jusqu’à 4K 60, couleur 10 bits.",
"🦀 **Moteur natif en Rust.** Compositeur GPU, proxys, décodage matériel. La 4K se parcourt sans accroc.",
"🤖 **Scriptable.** API JSON-RPC, gRPC et MCP, plus une CLI. Les agents IA peuvent monter de la vidéo avec.",
"🖥️ **macOS, Windows, Linux, Android.** 14 langues. La même appli, les mêmes fichiers de projet.",
],
download_h="Téléchargement", two_ways="Deux portes d’entrée :",
website="Le site web", website_text="vous donne la bonne version pour votre machine. Commencez ici.",
releases_text="propose chaque version pour chaque plateforme, avec installeurs, paquets et sommes de contrôle. Pour quand vous voulez choisir.",
beta="Concat est en **bêta** : ça marche, et il reste des angles. [Dites-le](https://github.com/jub0t/Concat/issues) quand vous en trouvez un.",
platforms="Plateformes",
win="x86_64 et ARM. Un installeur et un `.msi`. Si SmartScreen bloque une version non signée : **Informations complémentaires** › **Exécuter quand même**",
mac="Intel et Apple Silicon. Si macOS refuse d’ouvrir une version non signée : `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 et ARM. `.deb`, `.rpm`, `.AppImage` et un paquet Arch. Aussi un Flatpak sur **[Flatpark](https://flatpark.org/apps/app.concat.editor/)**, un dépôt Flatpak communautaire qui empaquette le `.deb` x86_64 de chaque version et se met à jour avec elle",
android="téléphones et tablettes", ios="iPhone et iPad, en sideload",
legend="✅ Pris en charge · 🚧 En cours · 🧪 À tester",
sysreq="La **configuration requise** et la taille des modèles optionnels sont sur [le site web](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Premiers pas", start1="Téléchargez, ouvrez, déposez vos rushes, montez. Pas de compte, pas de configuration.",
reporting="Pour signaler quelque chose :", reporting_text="chaque lancement écrit un journal, et Réglages › À propos a le bouton qui l’ouvre, à côté de celui qui copie les informations de votre système. Joignez les deux à une [issue](https://github.com/jub0t/Concat/issues) et le rapport arrive avec tout ce qu’il lui faut. Les dix derniers lancements sont conservés, celui d’hier est donc encore là ; rien n’est jamais envoyé nulle part tout seul.",
contribute_h="Contribuer",
contrib1="La meilleure façon de contribuer est de prendre une version sur la page [Releases](https://github.com/jub0t/Concat/releases) et de s’en servir : trouvez où ça casse, et dites où ça pourrait être mieux.",
contrib2="Prêt à écrire du code ? [CONTRIBUTING.md](../CONTRIBUTING.md) couvre l’installation, l’organisation de l’arborescence, les vérifications à lancer et la licence des contributions. Vous pilotez Concat depuis un script, un service ou un agent ? [La documentation développeur](https://concatenate.pages.dev/docs) couvre l’API Concat et ses transports : JSON-RPC, gRPC et MCP. [Cette Discussion](https://github.com/jub0t/Concat/discussions/3) est celle où le projet a été annoncé.",
contrib3="Les contributeurs peuvent demander un rôle `@Contributor` sur le serveur Discord, il suffit de le demander.",
contributors_h="Contributeurs", stars_h="Historique des étoiles",
sponsoring_h="Sponsoring",
sponsoring1="Concat n’a pas de paywall et n’en aura jamais : pas de filigrane, pas de compte, pas d’offre payante. Le sponsoring en tient lieu. Si Concat a remplacé un abonnement pour vous, une fraction de celui-ci le fait vivre.",
where_h="Où ça va", where_text="La [feuille de route](https://concatenate.pages.dev/roadmap) détaille ce que le sponsoring finance, et ce que coûte chaque pièce.",
payment_text='Choisissez un palier sur [le site web](https://concatenate.pages.dev/#sponsor).',
closing="Pas en mesure de participer ? Une étoile, un rapport de bug ou un mot à quelqu’un qui monte de la vidéo comptent beaucoup aussi.",
)
