CODE="de"
L=dict(name="Deutsch", flag="🇩🇪",
tagline="Der wirklich kostenlose, quelloffene CapCut-Ersatz für alle Plattformen.",
note="Übersetzt aus der englischen README vom 2. Oktober 2026. Die englische Fassung ist die, die aktuell gehalten wird.",
sponsors_h="Zahlende Sponsoren", proxyon="Pay-as-you-go-Proxys für Entwickler", proxyon_code="Mit dem Code <code>JUB0T</code> 20 % Rabatt",
logo_here="Dein Logo hier", sponsor_link="Sponsere Concat", slot="und dein Name, dein Logo und dein Link stehen an dieser Stelle",
about_h="Über Concat",
about1="Concat ist ein kostenloser, quelloffener Videoeditor und eine CapCut-Alternative für macOS, Windows, Linux und Android. Er kann das, wofür man CapCut tatsächlich öffnet: automatische Untertitel, Text-zu-Sprache, Hintergrundentfernung, Keyframe-Animation, Effekte und Titel, Schnitt auf mehreren Spuren, 4K-Export. Ohne die Haken: kein Wasserzeichen, kein Konto, kein Abo, kein Upload.",
about2="Alles läuft lokal auf einer nativen Rust-Engine mit GPU-Compositor. Installieren, Material hineinziehen, schneiden. Die KI-Modelle für Untertitel, Stimmen und Freisteller werden einmal in den Einstellungen geladen und arbeiten danach offline. Dein Material verlässt deine Festplatte nie.",
good_for="Gut für:", good_for_list="TikTok, Reels und Shorts, YouTube-Videos, Tutorials und Bildschirmaufnahmen, Podcast-Clips, Memes.",
machines="Auch für Maschinen:", machines_text="eine JSON-RPC-, gRPC- und MCP-API, damit auch Skripte und KI-Agenten damit Video schneiden können.",
highlights_h="Highlights",
highlights=[
"🚫 **Keine Wasserzeichen. Kein Konto. Keine Bezahlschranke.** Niemals.",
"🔒 **100 % lokal.** Nichts wird hochgeladen. Funktioniert offline.",
"💬 **Automatische Untertitel.** Lokales Whisper. Modellgröße wählen, gestylte Untertitel auf der Zeitleiste bekommen.",
"🗣️ **Text-zu-Sprache + Stimmklonen.** Kostenlose lokale Stimmen, oder jede Stimme aus ein paar Sekunden Aufnahme.",
"🧍 **Hintergrundentfernung.** Personen, Objekte, oder die Maske selbst malen.",
"🎞️ **Keyframes.** Position, Skalierung, Drehung, Deckkraft, Lautstärke, Effektparameter. Kurveneditor eingebaut.",
"✨ **Über 170 Effekte, Filter, Übergänge und Textanimationen.** GPU-gerendert, live in der Vorschau.",
"✂️ **Schnell schneiden.** Teilen, trimmen, Ripple, zusammenführen, Standbild, Geschwindigkeit. Magnetische Zeitleiste, wenn du willst.",
"🎚️ **Mehrere Spuren, mehrere Zeitleisten.** Mehrere Schnitte in einem Projekt. Mischmodi, Zuschnitt, Spiegelungen.",
"📝 **Titel.** Schriften, Kontur, Schatten, Hintergrundplatte. Vorlagen zum Loslegen.",
"🎙️ **Stimmbereinigung mit einem Schalter.** Entrauschen, Stimme verbessern, Lautheit angleichen. Dazu Chipmunk, Roboter, Telefon und Freunde.",
"📤 **Export.** H.264, HEVC, AV1. Bis 4K 60, 10-Bit-Farbe.",
"🦀 **Native Rust-Engine.** GPU-Compositor, Proxys, Hardware-Decoding. 4K scrubbt flüssig.",
"🤖 **Skriptbar.** JSON-RPC-, gRPC- und MCP-API plus CLI. KI-Agenten können damit Video schneiden.",
"🖥️ **macOS, Windows, Linux, Android.** 14 Sprachen. Dieselbe App, dieselben Projektdateien.",
],
download_h="Download", two_ways="Zwei Wege hinein:",
website="Die Website", website_text="gibt dir den passenden Build für deinen Rechner. Fang hier an.",
releases_text="hat jeden Build für jede Plattform, mit Installern, Paketen und Prüfsummen. Für den Fall, dass du selbst wählen willst.",
beta="Concat ist in der **Beta**: Es funktioniert, hat aber noch Kanten. [Sag Bescheid](https://github.com/jub0t/Concat/issues), wenn du eine findest.",
platforms="Plattformen",
win="x86_64 und ARM. Ein Setup und eine `.msi`. Wenn SmartScreen einen unsignierten Build stoppt: **Weitere Informationen** › **Trotzdem ausführen**",
mac="Intel und Apple Silicon. Wenn macOS einen unsignierten Build nicht öffnen will: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 und ARM. `.deb`, `.rpm`, `.AppImage` und ein Arch-Paket. Außerdem ein Flatpak auf **[Flatpark](https://flatpark.org/apps/app.concat.editor/)**, einem Community-Flatpak-Remote, das die x86_64-`.deb` jeder Version verpackt und mit ihr aktualisiert",
android="Telefone und Tablets", ios="iPhone und iPad, per Sideload",
legend="✅ Unterstützt · 🚧 In Arbeit · 🧪 Noch zu testen",
sysreq="**Systemanforderungen** und die Größen der optionalen Modelle stehen auf [der Website](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Loslegen", start1="Herunterladen, öffnen, Material hineinziehen, schneiden. Kein Konto, keine Einrichtung.",
reporting="Etwas melden:", reporting_text="Jeder Lauf schreibt ein Protokoll, und unter Einstellungen › Über gibt es den Knopf, der es öffnet, neben dem, der deine Systeminformationen kopiert. Häng beides an ein [Issue](https://github.com/jub0t/Concat/issues), und der Bericht kommt mit allem an, was er braucht. Die letzten zehn Läufe werden aufbewahrt, der von gestern ist also noch da; nichts wird je von selbst irgendwohin geschickt.",
contribute_h="Mitmachen",
contrib1="Am besten hilfst du, indem du dir einen Build von der [Releases](https://github.com/jub0t/Concat/releases)-Seite holst und ihn benutzt: finde, wo er bricht, und sag, wo er besser sein könnte.",
contrib2="Bereit, Code zu schreiben? [CONTRIBUTING.md](../CONTRIBUTING.md) beschreibt die Einrichtung, den Aufbau des Baums, die auszuführenden Prüfungen und wie Beiträge lizenziert werden. Du steuerst Concat aus einem Skript, einem Dienst oder einem Agenten? [Die Entwicklerdokumentation](https://concatenate.pages.dev/docs) beschreibt die Concat-API und ihre Transporte: JSON-RPC, gRPC und MCP. [In dieser Discussion](https://github.com/jub0t/Concat/discussions/3) wurde das Projekt angekündigt.",
contrib3="Mitwirkende können sich auf dem Discord-Server eine `@Contributor`-Rolle holen, einfach danach fragen.",
contributors_h="Mitwirkende", stars_h="Sternverlauf",
sponsoring_h="Sponsoring",
sponsoring1="Concat hat keine Bezahlschranke und wird nie eine haben: kein Wasserzeichen, kein Konto, keine Bezahlstufe. Sponsoring ist das, was an deren Stelle tritt. Wenn Concat für dich ein Abo ersetzt hat, hält ein Bruchteil davon es am Laufen.",
where_h="Wofür es verwendet wird", where_text="Die [Roadmap](https://concatenate.pages.dev/roadmap) zeigt, was Sponsoring bezahlt und was jedes Stück kostet.",
payment_text='Wähle eine Stufe auf [der Website](https://concatenate.pages.dev/#sponsor).',
closing="Gerade nicht in der Lage, etwas beizusteuern? Ein Stern, ein Fehlerbericht oder ein Wort an jemanden, der Video schneidet, zählt auch eine Menge.",
)
