CODE="ja"
L=dict(name="日本語", flag="🇯🇵",
tagline="本当に無料で、オープンソースのクロスプラットフォーム CapCut 代替。",
note="2026 年 10 月 2 日時点の英語版 README からの翻訳です。最新の内容は英語版が保持します。",
sponsors_h="有料スポンサー", proxyon="開発者向けの従量課金プロキシ", proxyon_code="コード <code>JUB0T</code> で 20 % オフ",
logo_here="あなたのロゴをここに", sponsor_link="Concat をスポンサーする", slot="と、あなたの名前・ロゴ・リンクがこの枠に載ります",
about_h="概要",
about1="Concat は macOS・Windows・Linux・Android 向けの、無料でオープンソースの動画エディタであり、CapCut の代替です。人々が実際に CapCut を開く目的をカバーします。自動字幕、テキスト読み上げ、背景除去、キーフレームアニメーション、エフェクトとタイトル、マルチトラック編集、4K 書き出し。しかも落とし穴なし。透かしなし、アカウント不要、サブスクリプション不要、アップロードなし。",
about2="すべてが GPU コンポジターを備えたネイティブ Rust エンジン上でローカルに動きます。インストールして、素材を放り込んで、切る。字幕・音声・切り抜き用の AI モデルは設定から一度だけダウンロードし、以降はオフラインで動作します。あなたの素材がディスクの外へ出ることはありません。",
good_for="向いている用途:", good_for_list="TikTok・Reels・Shorts、YouTube 動画、チュートリアルや画面収録、ポッドキャストの切り抜き、ミーム。",
machines="機械にも:", machines_text="JSON-RPC・gRPC・MCP の API があるので、スクリプトや AI エージェントも動画を編集できます。",
highlights_h="特長",
highlights=[
"🚫 **透かしなし。アカウント不要。有料の壁なし。** 永久に。",
"🔒 **100 % ローカル。** 何もアップロードしません。オフラインで動作。",
"💬 **自動字幕。** ローカルの Whisper。モデルサイズを選べば、スタイル付きの字幕がタイムラインに並びます。",
"🗣️ **テキスト読み上げ + 音声クローン。** 無料のローカル音声、または数秒の録音から任意の声を。",
"🧍 **背景除去。** 人物、物体、あるいは自分でマスクを描く。",
"🎞️ **キーフレーム。** 位置、拡大率、回転、不透明度、音量、エフェクトのパラメーター。カーブエディター内蔵。",
"✨ **170 以上のエフェクト、フィルター、トランジション、テキストアニメーション。** GPU で描画、プレビューにリアルタイム反映。",
"✂️ **素早く切る。** 分割、トリム、リップル、結合、フリーズフレーム、速度。お好みでマグネットタイムライン。",
"🎚️ **マルチトラック、マルチタイムライン。** 1 つのプロジェクトに複数の編集。ブレンドモード、クロップ、反転。",
"📝 **タイトル。** フォント、縁取り、影、背景プレート。出発点になるプリセット。",
"🎙️ **スイッチ 1 つで音声クリーンアップ。** ノイズ除去、声の強調、ラウドネスの均一化。さらにチップマンク、ロボット、電話などの声も。",
"📤 **書き出し。** H.264、HEVC、AV1。最大 4K 60、10 ビットカラー。",
"🦀 **ネイティブ Rust エンジン。** GPU コンポジター、プロキシ、ハードウェアデコード。4K もなめらかにスクラブ。",
"🤖 **スクリプト対応。** JSON-RPC・gRPC・MCP の API と CLI。AI エージェントが動画を編集できます。",
"🖥️ **macOS、Windows、Linux、Android。** 14 言語。同じアプリ、同じプロジェクトファイル。",
],
download_h="ダウンロード", two_ways="入口は 2 つ:",
website="ウェブサイト", website_text="があなたのマシンに合ったビルドを渡します。まずはここから。",
releases_text="にはすべてのプラットフォーム向けのすべてのビルドが、インストーラー、パッケージ、チェックサムとともにあります。自分で選びたいときに。",
beta="Concat は **ベータ版** です。動きますが、まだ粗い部分があります。見つけたら [教えてください](https://github.com/jub0t/Concat/issues)。",
platforms="プラットフォーム",
win="x86_64 と ARM。セットアップと `.msi`。SmartScreen が未署名ビルドを止めたら: **詳細情報** › **実行**",
mac="Intel と Apple シリコン。macOS が未署名ビルドを開かないときは: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 と ARM。`.deb`、`.rpm`、`.AppImage`、Arch パッケージ。さらに **[Flatpark](https://flatpark.org/apps/app.concat.editor/)** 上の Flatpak も。各リリースの x86_64 `.deb` を包み、リリースに合わせて更新されるコミュニティ運営の Flatpak リモートです",
android="スマートフォンとタブレット", ios="iPhone と iPad、サイドロード",
legend="✅ 対応 · 🚧 作業中 · 🧪 検証待ち",
sysreq="**システム要件** と任意モデルのサイズは [ウェブサイト](https://concatenate.pages.dev/guides/system-requirements) にあります。",
start_h="はじめに", start1="ダウンロードして、開いて、素材を放り込んで、切る。アカウントも設定も不要。",
reporting="何かを報告するには:", reporting_text="起動のたびにログが書かれ、設定 › 情報 にはそれを開くボタンと、システム情報をコピーするボタンがあります。両方を [issue](https://github.com/jub0t/Concat/issues) に添付すれば、必要なものがそろった報告になります。直近 10 回分が保存されるので昨日の分も残っています。勝手にどこかへ送られることはありません。",
contribute_h="貢献するには",
contrib1="いちばんの貢献は、[Releases](https://github.com/jub0t/Concat/releases) ページからビルドを取って使うことです。どこで壊れるかを見つけ、どこがもっと良くなるかを伝えてください。",
contrib2="コードを書く準備ができたら、[CONTRIBUTING.md](../CONTRIBUTING.md) にセットアップ、ツリーの構成、実行すべきチェック、貢献のライセンスがまとまっています。スクリプトやサービス、エージェントから Concat を動かすなら、[開発者向けドキュメント](https://concatenate.pages.dev/docs) に Concat API とそのトランスポート (JSON-RPC、gRPC、MCP) があります。プロジェクトは [この Discussion](https://github.com/jub0t/Concat/discussions/3) で発表されました。",
contrib3="貢献者は Discord サーバーで `@Contributor` ロールを受け取れます。声をかけてください。",
contributors_h="貢献者", stars_h="スターの推移",
sponsoring_h="スポンサー",
sponsoring1="Concat に有料の壁はなく、これからもありません。透かしなし、アカウント不要、有料プランなし。その代わりがスポンサーです。Concat があなたのサブスクリプションの代わりになったなら、その一部で Concat は続いていけます。",
where_h="使い道", where_text="[ロードマップ](https://concatenate.pages.dev/roadmap) に、スポンサー費用で何を進めるか、それぞれにいくらかかるかが載っています。",
payment_text='[ウェブサイト](https://concatenate.pages.dev/#sponsor) でティアを選んでください。',
closing="今は支援できなくても、スター、バグ報告、動画を編集する誰かへの一言も大きな力になります。",
)
