CODE="vi"
L=dict(name="Tiếng Việt", flag="🇻🇳",
tagline="Lựa chọn thay thế CapCut đa nền tảng, thực sự miễn phí và mã nguồn mở.",
note="Dịch từ README tiếng Anh ngày 2 tháng 10 năm 2026. Bản tiếng Anh là bản được cập nhật thường xuyên.",
sponsors_h="Nhà tài trợ trả phí", proxyon="Proxy trả theo mức dùng cho lập trình viên", proxyon_code="Dùng mã <code>JUB0T</code> để giảm 20 %",
logo_here="Logo của bạn ở đây", sponsor_link="Tài trợ Concat", slot="và tên, logo cùng liên kết của bạn sẽ ở vị trí này",
about_h="Giới thiệu",
about1="Concat là trình biên tập video miễn phí, mã nguồn mở và là lựa chọn thay thế CapCut cho macOS, Windows, Linux và Android. Nó làm được những việc mà người ta thực sự mở CapCut để làm: phụ đề tự động, chuyển văn bản thành giọng nói, xóa nền, hoạt ảnh keyframe, hiệu ứng và tiêu đề, cắt nhiều track, xuất 4K. Không có bất kỳ ràng buộc nào: không watermark, không tài khoản, không đăng ký, không tải lên.",
about2="Mọi thứ chạy cục bộ trên engine Rust gốc với trình tổng hợp GPU. Cài đặt, kéo thả footage, cắt. Các mô hình AI cho phụ đề, giọng nói và tách nền tải một lần từ Cài đặt và sau đó hoạt động ngoại tuyến. Footage của bạn không bao giờ rời khỏi ổ đĩa của bạn.",
good_for="Phù hợp cho:", good_for_list="TikTok, Reels và Shorts, video YouTube, hướng dẫn và ghi màn hình, trích đoạn podcast, meme.",
machines="Cũng dành cho máy móc:", machines_text="API JSON-RPC, gRPC và MCP, để script và các tác nhân AI cũng có thể cắt video bằng nó.",
highlights_h="Điểm nổi bật",
highlights=[
"🚫 **Không watermark. Không tài khoản. Không tường phí.** Mãi mãi.",
"🔒 **100 % cục bộ.** Không tải lên gì cả. Hoạt động ngoại tuyến.",
"💬 **Phụ đề tự động.** Whisper cục bộ. Chọn kích thước mô hình, nhận phụ đề có kiểu dáng trên timeline.",
"🗣️ **Chuyển văn bản thành giọng nói + nhân bản giọng.** Giọng cục bộ miễn phí, hoặc bất kỳ giọng nào từ vài giây ghi âm.",
"🧍 **Xóa nền.** Người, vật thể, hoặc tự vẽ mặt nạ.",
"🎞️ **Keyframe.** Vị trí, tỷ lệ, xoay, độ mờ, âm lượng, tham số hiệu ứng. Trình chỉnh sửa đường cong tích hợp.",
"✨ **Hơn 170 hiệu ứng, bộ lọc, chuyển cảnh và hoạt ảnh chữ.** Kết xuất bằng GPU, xem trực tiếp trong bản xem trước.",
"✂️ **Cắt nhanh.** Tách, cắt gọt, ripple, gộp, đóng băng khung hình, tốc độ. Timeline từ tính nếu bạn muốn.",
"🎚️ **Nhiều track, nhiều timeline.** Nhiều bản dựng trong một dự án. Chế độ hòa trộn, cắt khung, lật.",
"📝 **Tiêu đề.** Phông chữ, viền, bóng đổ, nền. Preset để bắt đầu.",
"🎙️ **Làm sạch giọng nói bằng một công tắc.** Khử ồn, tăng cường giọng, cân bằng âm lượng. Thêm giọng sóc, robot, điện thoại và các bạn.",
"📤 **Xuất.** H.264, HEVC, AV1. Lên đến 4K 60, màu 10-bit.",
"🦀 **Engine Rust gốc.** Trình tổng hợp GPU, proxy, giải mã phần cứng. Tua 4K mượt mà.",
"🤖 **Có thể lập trình.** API JSON-RPC, gRPC và MCP, cùng CLI. Các tác nhân AI có thể cắt video bằng nó.",
"🖥️ **macOS, Windows, Linux, Android.** 14 ngôn ngữ. Cùng một ứng dụng, cùng tệp dự án.",
],
download_h="Tải về", two_ways="Hai cách:",
website="Trang web", website_text="đưa bạn đúng bản dựng cho máy của bạn. Bắt đầu từ đây.",
releases_text="có mọi bản dựng cho mọi nền tảng, kèm trình cài đặt, gói và checksum. Khi bạn muốn tự chọn.",
beta="Concat đang ở giai đoạn **beta**: nó hoạt động, và vẫn còn vài góc cạnh. [Hãy cho biết](https://github.com/jub0t/Concat/issues) khi bạn gặp một lỗi.",
platforms="Nền tảng",
win="x86_64 và ARM. Một bộ cài và một `.msi`. Nếu SmartScreen chặn bản dựng chưa ký: **More info** › **Run anyway**",
mac="Intel và Apple Silicon. Nếu macOS từ chối mở bản dựng chưa ký: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 và ARM. `.deb`, `.rpm`, `.AppImage` và gói Arch. Ngoài ra còn Flatpak trên **[Flatpark](https://flatpark.org/apps/app.concat.editor/)**, một kho Flatpak cộng đồng đóng gói `.deb` x86_64 của mỗi bản phát hành và cập nhật theo nó",
android="điện thoại và máy tính bảng", ios="iPhone và iPad, qua sideload",
legend="✅ Được hỗ trợ · 🚧 Đang thực hiện · 🧪 Cần kiểm thử",
sysreq="**Yêu cầu hệ thống** và kích thước các mô hình tùy chọn có trên [trang web](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Bắt đầu", start1="Tải về, mở, kéo thả footage, cắt. Không tài khoản, không thiết lập.",
reporting="Báo cáo sự cố:", reporting_text="mỗi lần chạy đều ghi nhật ký, và Cài đặt › Giới thiệu có nút mở nhật ký cùng nút sao chép thông tin hệ thống của bạn. Đính kèm cả hai vào một [issue](https://github.com/jub0t/Concat/issues) và báo cáo sẽ đến với đầy đủ những gì cần thiết. Mười lần chạy gần nhất được giữ lại, nên của hôm qua vẫn còn; không có gì tự gửi đi đâu cả.",
contribute_h="Cách đóng góp",
contrib1="Cách đóng góp tốt nhất là lấy một bản dựng từ trang [Releases](https://github.com/jub0t/Concat/releases) và dùng nó: tìm chỗ nó hỏng, và nói chỗ nó có thể tốt hơn.",
contrib2="Sẵn sàng viết mã? [CONTRIBUTING.md](../CONTRIBUTING.md) mô tả cách thiết lập, bố cục cây mã nguồn, các kiểm tra cần chạy và cách cấp phép cho đóng góp. Điều khiển Concat từ script, dịch vụ hay tác nhân? [Tài liệu dành cho nhà phát triển](https://concatenate.pages.dev/docs) mô tả API của Concat và các phương thức truyền tải: JSON-RPC, gRPC và MCP. [Thảo luận này](https://github.com/jub0t/Concat/discussions/3) là nơi dự án được công bố.",
contrib3="Người đóng góp có thể nhận vai trò `@Contributor` trên máy chủ Discord, chỉ cần hỏi.",
contributors_h="Người đóng góp", stars_h="Lịch sử sao",
sponsoring_h="Tài trợ",
sponsoring1="Concat không có tường phí và sẽ không bao giờ có: không watermark, không tài khoản, không gói trả phí. Tài trợ là thứ thay thế cho điều đó. Nếu Concat đã thay thế một gói đăng ký của bạn, một phần nhỏ của gói đó sẽ giúp nó tiếp tục.",
where_h="Tiền đi về đâu", where_text="[Lộ trình](https://concatenate.pages.dev/roadmap) trình bày tài trợ chi trả cho những gì, và mỗi phần tốn bao nhiêu.",
payment_text='Chọn một mức trên [trang web](https://concatenate.pages.dev/#sponsor).',
closing="Chưa thể đóng góp? Một ngôi sao, một báo cáo lỗi, hay một lời giới thiệu với ai đó làm video cũng rất đáng quý.",
)
