CODE="zh-Hans"
L=dict(name="简体中文", flag="🇨🇳",
tagline="真正免费、开源、跨平台的 CapCut 替代品。",
note="译自 2026 年 10 月 2 日的英文 README。以英文版为准，它才是持续更新的版本。",
sponsors_h="付费赞助商", proxyon="面向开发者的按量付费代理", proxyon_code="使用代码 <code>JUB0T</code> 享 20 % 折扣",
logo_here="您的 Logo 放这里", sponsor_link="赞助 Concat", slot="您的名字、Logo 和链接就会出现在这个位置",
about_h="关于",
about1="Concat 是一款免费、开源的视频编辑器，是 macOS、Windows、Linux 和 Android 上的 CapCut 替代品。它覆盖了人们真正打开 CapCut 要做的事：自动字幕、文字转语音、背景移除、关键帧动画、特效与标题、多轨剪辑、4K 导出。而且没有任何套路：无水印、无需账号、无需订阅、不上传。",
about2="一切都在本地运行，基于带 GPU 合成器的原生 Rust 引擎。安装、拖入素材、开剪。字幕、语音和抠像所用的 AI 模型只需在设置中下载一次，之后离线可用。您的素材永远不会离开您的硬盘。",
good_for="适合：", good_for_list="TikTok、Reels 和 Shorts，YouTube 视频，教程与屏幕录制，播客片段，表情包。",
machines="也适合机器：", machines_text="提供 JSON-RPC、gRPC 和 MCP API，脚本和 AI 代理同样可以用它剪视频。",
highlights_h="亮点",
highlights=[
"🚫 **无水印。无账号。无付费墙。** 永远如此。",
"🔒 **100 % 本地。** 不上传任何内容。离线可用。",
"💬 **自动字幕。** 本地 Whisper。选一个模型大小，带样式的字幕就排进时间线。",
"🗣️ **文字转语音 + 声音克隆。** 免费的本地声音，或用几秒钟录音克隆任何声音。",
"🧍 **背景移除。** 人物、物体，或者自己涂抹遮罩。",
"🎞️ **关键帧。** 位置、缩放、旋转、不透明度、音量、特效参数。内置曲线编辑器。",
"✨ **170 多种特效、滤镜、转场和文字动画。** GPU 渲染，预览中实时呈现。",
"✂️ **快剪。** 分割、修剪、涟漪、合并、定格、变速。想要的话还有磁性时间线。",
"🎚️ **多轨道、多时间线。** 一个项目里放多个剪辑版本。混合模式、裁剪、翻转。",
"📝 **标题。** 字体、描边、阴影、背景底板。有预设可作起点。",
"🎙️ **一键人声净化。** 降噪、增强人声、响度均衡。还有花栗鼠、机器人、电话等效果。",
"📤 **导出。** H.264、HEVC、AV1。最高 4K 60，10 位色彩。",
"🦀 **原生 Rust 引擎。** GPU 合成器、代理、硬件解码。4K 拖动也顺滑。",
"🤖 **可脚本化。** JSON-RPC、gRPC 和 MCP API，外加 CLI。AI 代理可以用它剪视频。",
"🖥️ **macOS、Windows、Linux、Android。** 14 种语言。同一个应用，同样的项目文件。",
],
download_h="下载", two_ways="两个入口：",
website="官网", website_text="会给您适合您机器的版本。从这里开始。",
releases_text="有每个平台的每个版本，附带安装程序、软件包和校验和。想自己挑选时用它。",
beta="Concat 处于 **测试版**：能用，但还有毛边。遇到了请 [告诉我们](https://github.com/jub0t/Concat/issues)。",
platforms="平台",
win="x86_64 和 ARM。安装程序和 `.msi`。如果 SmartScreen 拦截未签名版本：**更多信息** › **仍要运行**",
mac="Intel 和 Apple 芯片。如果 macOS 拒绝打开未签名版本：`xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 和 ARM。`.deb`、`.rpm`、`.AppImage` 和 Arch 软件包。另有 **[Flatpark](https://flatpark.org/apps/app.concat.editor/)** 上的 Flatpak，这是一个社区 Flatpak 仓库，封装每个版本的 x86_64 `.deb` 并随之更新",
android="手机和平板", ios="iPhone 和 iPad，需侧载",
legend="✅ 已支持 · 🚧 开发中 · 🧪 待测试",
sysreq="**系统要求** 和可选模型的大小见 [官网](https://concatenate.pages.dev/guides/system-requirements)。",
start_h="开始使用", start1="下载、打开、拖入素材、开剪。无需账号，无需设置。",
reporting="反馈问题：", reporting_text="每次运行都会写日志，设置 › 关于 里有打开日志的按钮，旁边是复制系统信息的按钮。把两者附到一个 [issue](https://github.com/jub0t/Concat/issues) 里，报告就带齐了所需的一切。保留最近十次运行，所以昨天的还在；任何内容都不会自动发送到任何地方。",
contribute_h="如何贡献",
contrib1="最好的贡献方式是从 [Releases](https://github.com/jub0t/Concat/releases) 页面拿一个版本来用：找到它哪里会坏，说出它哪里可以更好。",
contrib2="准备写代码了？[CONTRIBUTING.md](../CONTRIBUTING.md) 介绍了环境搭建、目录结构、要运行的检查以及贡献的许可方式。要从脚本、服务或代理驱动 Concat？[开发者文档](https://concatenate.pages.dev/docs) 介绍了 Concat API 及其传输方式：JSON-RPC、gRPC 和 MCP。项目在 [这个 Discussion](https://github.com/jub0t/Concat/discussions/3) 里发布。",
contrib3="贡献者可以在 Discord 服务器申请 `@Contributor` 身份组，开口要就行。",
contributors_h="贡献者", stars_h="Star 历史",
sponsoring_h="赞助",
sponsoring1="Concat 没有付费墙，以后也不会有：无水印、无账号、无付费档。赞助就是替代它的方式。如果 Concat 替您省下了一份订阅，拿出其中一小部分就能让它继续走下去。",
where_h="钱用在哪", where_text="[路线图](https://concatenate.pages.dev/roadmap) 列出了赞助用于哪些事，以及每一项的花费。",
payment_text='在 [官网](https://concatenate.pages.dev/#sponsor) 选一个档位。',
closing="暂时不方便出力？一个 Star、一份 bug 报告，或者向剪视频的朋友提一句，同样意义重大。",
)
