CODE="tr"
L=dict(name="Türkçe", flag="🇹🇷",
tagline="Gerçekten ücretsiz, açık kaynaklı ve çok platformlu CapCut alternatifi.",
note="İngilizce README’den 2 Ekim 2026’da çevrildi. Güncel tutulan sürüm İngilizce olandır.",
sponsors_h="Ücretli Sponsorlar", proxyon="Geliştiriciler için kullandıkça öde proxy’ler", proxyon_code="<code>JUB0T</code> koduyla %20 indirim",
logo_here="Logonuz burada", sponsor_link="Concat’e sponsor olun", slot="ve adınız, logonuz ve bağlantınız bu yeri alsın",
about_h="Hakkında",
about1="Concat; macOS, Windows, Linux ve Android için ücretsiz, açık kaynaklı bir video düzenleyici ve bir CapCut alternatifidir. İnsanların CapCut’ı gerçekten ne için açtıklarını karşılar: otomatik altyazı, metinden sese, arka plan kaldırma, anahtar kare animasyonu, efektler ve yazılar, çok parçalı kurgu, 4K dışa aktarma. Hiçbir tuzak olmadan: filigran yok, hesap yok, abonelik yok, yükleme yok.",
about2="Her şey, GPU birleştiricili yerel bir Rust motorunda yerel olarak çalışır. Kurun, görüntüleri bırakın, kesin. Altyazı, ses ve kesme için yapay zekâ modelleri Ayarlar’dan bir kez indirilir ve sonrasında çevrimdışı çalışır. Görüntüleriniz diskinizden asla çıkmaz.",
good_for="Şunlar için uygun:", good_for_list="TikTok, Reels ve Shorts, YouTube videoları, eğitimler ve ekran kayıtları, podcast kesitleri, memler.",
machines="Makineler için de:", machines_text="bir JSON-RPC, gRPC ve MCP API’si; böylece betikler ve yapay zekâ ajanları da onunla video kesebilir.",
highlights_h="Öne çıkanlar",
highlights=[
"🚫 **Filigran yok. Hesap yok. Ödeme duvarı yok.** Asla.",
"🔒 **%100 yerel.** Hiçbir şey yüklenmez. Çevrimdışı çalışır.",
"💬 **Otomatik altyazı.** Yerel Whisper. Bir model boyutu seçin, zaman çizelgesinde biçimli altyazılar alın.",
"🗣️ **Metinden sese + ses klonlama.** Ücretsiz yerel sesler ya da birkaç saniyelik kayıttan herhangi bir ses.",
"🧍 **Arka plan kaldırma.** İnsanlar, nesneler ya da maskeyi kendiniz boyayın.",
"🎞️ **Anahtar kareler.** Konum, ölçek, döndürme, saydamlık, ses düzeyi, efekt parametreleri. Yerleşik eğri düzenleyici.",
"✨ **170’ten fazla efekt, filtre, geçiş ve yazı animasyonu.** GPU ile çizilir, önizlemede canlı.",
"✂️ **Hızlı kesin.** Böl, kırp, ripple, birleştir, kareyi dondur, hız. İsterseniz manyetik zaman çizelgesi.",
"🎚️ **Çok parçalı, çok zaman çizelgeli.** Bir projede birden çok kurgu. Karışım modları, kırpma, çevirmeler.",
"📝 **Yazılar.** Yazı tipleri, kontur, gölge, arka plan plakası. Başlamak için hazır ayarlar.",
"🎙️ **Tek anahtarla ses temizliği.** Gürültü azaltma, sesi iyileştirme, ses düzeyini dengeleme. Artı sincap, robot, telefon ve arkadaşları.",
"📤 **Dışa aktarma.** H.264, HEVC, AV1. 4K 60’a kadar, 10 bit renk.",
"🦀 **Yerel Rust motoru.** GPU birleştirici, proxy’ler, donanım çözme. 4K akıcı gezinir.",
"🤖 **Betiklenebilir.** JSON-RPC, gRPC ve MCP API’si, artı bir CLI. Yapay zekâ ajanları onunla video kesebilir.",
"🖥️ **macOS, Windows, Linux, Android.** 14 dil. Aynı uygulama, aynı proje dosyaları.",
],
download_h="İndir", two_ways="İki yol var:",
website="Web sitesi", website_text="makineniz için doğru derlemeyi verir. Buradan başlayın.",
releases_text="her platform için her derlemeyi kurucular, paketler ve sağlama toplamlarıyla sunar. Kendiniz seçmek istediğinizde.",
beta="Concat **beta** aşamasında: çalışıyor, ama hâlâ pürüzleri var. Bir tane bulduğunuzda [söyleyin](https://github.com/jub0t/Concat/issues).",
platforms="Platformlar",
win="x86_64 ve ARM. Bir kurulum ve bir `.msi`. SmartScreen imzasız bir derlemeyi durdurursa: **Daha fazla bilgi** › **Yine de çalıştır**",
mac="Intel ve Apple Silicon. macOS imzasız bir derlemeyi açmayı reddederse: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 ve ARM. `.deb`, `.rpm`, `.AppImage` ve bir Arch paketi. Ayrıca her sürümün x86_64 `.deb`’ini saran ve onunla güncellenen topluluk Flatpak deposu **[Flatpark](https://flatpark.org/apps/app.concat.editor/)** üzerinde bir Flatpak",
android="telefonlar ve tabletler", ios="iPhone ve iPad, sideload ile",
legend="✅ Destekleniyor · 🚧 Çalışılıyor · 🧪 Test edilecek",
sysreq="**Sistem gereksinimleri** ve isteğe bağlı model boyutları [web sitesinde](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Başlarken", start1="İndirin, açın, görüntüleri bırakın, kesin. Hesap yok, kurulum yok.",
reporting="Bir şey bildirmek için:", reporting_text="her çalıştırma bir günlük yazar ve Ayarlar › Hakkında’da onu açan düğme, sistem bilgilerinizi kopyalayan düğmenin yanındadır. İkisini de bir [issue](https://github.com/jub0t/Concat/issues)’a ekleyin; rapor ihtiyacı olan her şeyle gelir. Son on çalıştırma saklanır, yani dünkü hâlâ orada; hiçbir şey kendiliğinden hiçbir yere gönderilmez.",
contribute_h="Nasıl katkıda bulunulur",
contrib1="Katkıda bulunmanın en iyi yolu [Releases](https://github.com/jub0t/Concat/releases) sayfasından bir derleme alıp kullanmaktır: nerede bozulduğunu bulun ve nerede daha iyi olabileceğini söyleyin.",
contrib2="Kod yazmaya hazır mısınız? [CONTRIBUTING.md](../CONTRIBUTING.md) kurulumu, ağacın düzenini, çalıştırılacak denetimleri ve katkıların nasıl lisanslandığını anlatır. Concat’i bir betikten, servisten ya da ajandan mı sürüyorsunuz? [Geliştirici belgeleri](https://concatenate.pages.dev/docs) Concat API’sini ve taşıyıcılarını anlatır: JSON-RPC, gRPC ve MCP. Proje [bu tartışmada](https://github.com/jub0t/Concat/discussions/3) duyuruldu.",
contrib3="Katkıda bulunanlar Discord sunucusunda bir `@Contributor` rolü alabilir, istemeniz yeter.",
contributors_h="Katkıda bulunanlar", stars_h="Yıldız geçmişi",
sponsoring_h="Sponsorluk",
sponsoring1="Concat’in ödeme duvarı yok ve asla olmayacak: filigran yok, hesap yok, ücretli katman yok. Sponsorluk onun yerini tutar. Concat sizin için bir aboneliğin yerine geçtiyse, onun küçük bir kısmı Concat’i ayakta tutar.",
where_h="Nereye gidiyor", where_text="[Yol haritası](https://concatenate.pages.dev/roadmap) sponsorluğun neyi karşıladığını ve her parçanın ne kadara mal olduğunu anlatır.",
payment_text='[Web sitesinde](https://concatenate.pages.dev/#sponsor) bir katman seçin.',
closing="Katkıda bulunacak durumda değil misiniz? Bir yıldız, bir hata bildirimi ya da video düzenleyen birine bir söz de çok şey ifade eder.",
)
