CODE="id"
L=dict(name="Bahasa Indonesia", flag="🇮🇩",
tagline="Pengganti CapCut lintas platform yang benar-benar gratis dan sumber terbuka.",
note="Diterjemahkan dari README bahasa Inggris pada 2 Oktober 2026. Versi bahasa Inggris adalah yang selalu diperbarui.",
sponsors_h="Sponsor Berbayar", proxyon="Proxy bayar sesuai pemakaian untuk pengembang", proxyon_code="Pakai kode <code>JUB0T</code> untuk diskon 20 %",
logo_here="Logo Anda di sini", sponsor_link="Sponsori Concat", slot="dan nama, logo, serta tautan Anda mengisi tempat ini",
about_h="Tentang",
about1="Concat adalah penyunting video gratis dan sumber terbuka, alternatif CapCut untuk macOS, Windows, Linux, dan Android. Ia mencakup hal-hal yang sebenarnya orang buka CapCut untuk: teks otomatis, teks ke suara, penghapusan latar, animasi keyframe, efek dan judul, pemotongan multi-trek, ekspor 4K. Tanpa jebakan apa pun: tanpa tanda air, tanpa akun, tanpa langganan, tanpa unggahan.",
about2="Semuanya berjalan lokal di mesin Rust native dengan kompositor GPU. Pasang, jatuhkan rekaman, potong. Model AI untuk teks, suara, dan pemotongan latar diunduh sekali dari Pengaturan dan setelah itu bekerja luring. Rekaman Anda tidak pernah meninggalkan disk Anda.",
good_for="Cocok untuk:", good_for_list="TikTok, Reels, dan Shorts, video YouTube, tutorial dan rekaman layar, klip podcast, meme.",
machines="Juga untuk mesin:", machines_text="API JSON-RPC, gRPC, dan MCP, sehingga skrip dan agen AI juga bisa memotong video dengannya.",
highlights_h="Sorotan",
highlights=[
"🚫 **Tanpa tanda air. Tanpa akun. Tanpa paywall.** Selamanya.",
"🔒 **100 % lokal.** Tidak ada yang diunggah. Bekerja luring.",
"💬 **Teks otomatis.** Whisper lokal. Pilih ukuran model, dapatkan teks bergaya di lini masa.",
"🗣️ **Teks ke suara + kloning suara.** Suara lokal gratis, atau suara apa pun dari rekaman beberapa detik.",
"🧍 **Penghapusan latar.** Orang, objek, atau lukis maskernya sendiri.",
"🎞️ **Keyframe.** Posisi, skala, rotasi, opasitas, volume, parameter efek. Penyunting kurva bawaan.",
"✨ **170+ efek, filter, transisi, dan animasi teks.** Dirender GPU, langsung di pratinjau.",
"✂️ **Potong cepat.** Belah, pangkas, ripple, gabung, bekukan bingkai, kecepatan. Lini masa magnetik kalau mau.",
"🎚️ **Multi-trek, multi-lini masa.** Beberapa potongan dalam satu proyek. Mode campur, crop, balik.",
"📝 **Judul.** Font, garis tepi, bayangan, pelat latar. Preset untuk memulai.",
"🎙️ **Pembersihan suara satu saklar.** Hilangkan derau, tingkatkan suara, ratakan kenyaringan. Plus tupai, robot, telepon, dan kawan-kawan.",
"📤 **Ekspor.** H.264, HEVC, AV1. Hingga 4K 60, warna 10-bit.",
"🦀 **Mesin Rust native.** Kompositor GPU, proxy, dekode perangkat keras. 4K digeser dengan mulus.",
"🤖 **Bisa diskrip.** API JSON-RPC, gRPC, dan MCP, plus CLI. Agen AI bisa memotong video dengannya.",
"🖥️ **macOS, Windows, Linux, Android.** 14 bahasa. Aplikasi yang sama, berkas proyek yang sama.",
],
download_h="Unduh", two_ways="Dua jalan masuk:",
website="Situs web", website_text="memberi Anda build yang tepat untuk mesin Anda. Mulai dari sini.",
releases_text="punya setiap build untuk setiap platform, dengan pemasang, paket, dan checksum. Untuk saat Anda ingin memilih sendiri.",
beta="Concat masih **beta**: ia bekerja, dan masih ada sisi kasarnya. [Beri tahu](https://github.com/jub0t/Concat/issues) saat Anda menemukannya.",
platforms="Platform",
win="x86_64 dan ARM. Sebuah setup dan `.msi`. Jika SmartScreen menghentikan build tanpa tanda tangan: **More info** › **Run anyway**",
mac="Intel dan Apple Silicon. Jika macOS menolak membuka build tanpa tanda tangan: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 dan ARM. `.deb`, `.rpm`, `.AppImage`, dan paket Arch. Juga Flatpak di **[Flatpark](https://flatpark.org/apps/app.concat.editor/)**, remote Flatpak komunitas yang membungkus `.deb` x86_64 setiap rilis dan ikut memperbarui bersamanya",
android="ponsel dan tablet", ios="iPhone dan iPad, lewat sideload",
legend="✅ Didukung · 🚧 Dalam pengerjaan · 🧪 Perlu diuji",
sysreq="**Kebutuhan sistem** dan ukuran model opsional ada di [situs web](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Memulai", start1="Unduh, buka, jatuhkan rekaman, potong. Tanpa akun, tanpa penyiapan.",
reporting="Melaporkan sesuatu:", reporting_text="setiap kali dijalankan ada log yang ditulis, dan Pengaturan › Tentang punya tombol yang membukanya di samping tombol yang menyalin informasi sistem Anda. Lampirkan keduanya ke sebuah [issue](https://github.com/jub0t/Concat/issues) dan laporan tiba dengan semua yang dibutuhkan. Sepuluh jalanan terakhir disimpan, jadi yang kemarin masih ada; tidak ada yang pernah dikirim ke mana pun dengan sendirinya.",
contribute_h="Cara berkontribusi",
contrib1="Cara terbaik berkontribusi adalah mengambil build dari halaman [Releases](https://github.com/jub0t/Concat/releases) dan memakainya: temukan di mana ia rusak, dan katakan di mana ia bisa lebih baik.",
contrib2="Siap menulis kode? [CONTRIBUTING.md](../CONTRIBUTING.md) membahas penyiapan, tata letak pohon, pemeriksaan yang dijalankan, dan bagaimana kontribusi dilisensikan. Mengendalikan Concat dari skrip, layanan, atau agen? [Dokumentasi pengembang](https://concatenate.pages.dev/docs) membahas API Concat dan transportnya: JSON-RPC, gRPC, dan MCP. [Diskusi ini](https://github.com/jub0t/Concat/discussions/3) adalah tempat proyek diumumkan.",
contrib3="Kontributor bebas meminta peran `@Contributor` di server Discord, cukup minta saja.",
contributors_h="Kontributor", stars_h="Riwayat bintang",
sponsoring_h="Sponsor",
sponsoring1="Concat tidak punya paywall dan tidak akan pernah: tanpa tanda air, tanpa akun, tanpa tingkat berbayar. Sponsorlah yang menggantikannya. Jika Concat telah menggantikan sebuah langganan bagi Anda, sebagian kecil darinya menjaga Concat tetap berjalan.",
where_h="Ke mana dananya", where_text="[Peta jalan](https://concatenate.pages.dev/roadmap) memaparkan apa yang dibiayai sponsor, dan berapa biaya tiap bagiannya.",
payment_text='Pilih tingkat di [situs web](https://concatenate.pages.dev/#sponsor).',
closing="Belum bisa ikut menyumbang? Sebuah bintang, laporan bug, atau sepatah kata kepada seseorang yang menyunting video juga sangat berarti.",
)
