CODE="es"
L=dict(name="Español", flag="🇪🇸",
tagline="El reemplazo de CapCut realmente gratuito, de código abierto y multiplataforma.",
note="Traducido del README en inglés el 2 de octubre de 2026. La versión en inglés es la que se mantiene al día.",
sponsors_h="Patrocinadores de pago", proxyon="Proxies de pago por uso para desarrolladores", proxyon_code="Usa el código <code>JUB0T</code> para un 20 % de descuento",
logo_here="Tu logo aquí", sponsor_link="Patrocina Concat", slot="y tu nombre, tu logo y tu enlace ocupan este espacio",
about_h="Acerca de",
about1="Concat es un editor de vídeo gratuito y de código abierto, una alternativa a CapCut para macOS, Windows, Linux y Android. Cubre lo que la gente realmente abre CapCut para hacer: subtítulos automáticos, texto a voz, eliminación de fondo, animación por fotogramas clave, efectos y títulos, corte multipista, exportación 4K. Sin trampas: sin marca de agua, sin cuenta, sin suscripción, sin subir nada.",
about2="Todo corre en local sobre un motor nativo en Rust con un compositor por GPU. Instálalo, suelta el material, corta. Los modelos de IA para subtítulos, voces y recorte se descargan una vez desde Ajustes y después funcionan sin conexión. Tu material nunca sale de tu disco.",
good_for="Bueno para:", good_for_list="TikTok, Reels y Shorts, vídeos de YouTube, tutoriales y grabaciones de pantalla, clips de pódcast, memes.",
machines="También para máquinas:", machines_text="una API JSON-RPC, gRPC y MCP, para que los scripts y los agentes de IA también puedan cortar vídeo con él.",
highlights_h="Lo más destacado",
highlights=[
"🚫 **Sin marcas de agua. Sin cuenta. Sin muro de pago.** Nunca.",
"🔒 **100 % local.** Nada se sube. Funciona sin conexión.",
"💬 **Subtítulos automáticos.** Whisper en local. Elige un tamaño de modelo y obtén subtítulos con estilo en la línea de tiempo.",
"🗣️ **Texto a voz + clonación de voz.** Voces locales gratuitas, o cualquier voz a partir de unos segundos de grabación.",
"🧍 **Eliminación de fondo.** Personas, objetos, o pinta la máscara tú mismo.",
"🎞️ **Fotogramas clave.** Posición, escala, rotación, opacidad, volumen, parámetros de efectos. Editor de curvas integrado.",
"✨ **Más de 170 efectos, filtros, transiciones y animaciones de texto.** Renderizados por GPU, en vivo en la vista previa.",
"✂️ **Corta rápido.** Dividir, recortar, ripple, unir, congelar fotograma, velocidad. Línea de tiempo magnética si la quieres.",
"🎚️ **Multipista, multilínea de tiempo.** Varios montajes en un proyecto. Modos de fusión, recorte, volteos.",
"📝 **Títulos.** Fuentes, trazo, sombra, placa de fondo. Preajustes para empezar.",
"🎙️ **Limpieza de voz con un interruptor.** Reducir ruido, realzar la voz, nivelar el volumen. Más ardilla, robot, teléfono y compañía.",
"📤 **Exportación.** H.264, HEVC, AV1. Hasta 4K 60, color de 10 bits.",
"🦀 **Motor nativo en Rust.** Compositor por GPU, proxies, decodificación por hardware. El 4K se desplaza con fluidez.",
"🤖 **Programable.** API JSON-RPC, gRPC y MCP, más una CLI. Los agentes de IA pueden cortar vídeo con él.",
"🖥️ **macOS, Windows, Linux, Android.** 14 idiomas. La misma app, los mismos archivos de proyecto.",
],
download_h="Descarga", two_ways="Dos formas de entrar:",
website="El sitio web", website_text="te da la compilación adecuada para tu máquina. Empieza aquí.",
releases_text="tiene todas las compilaciones para todas las plataformas, con instaladores, paquetes y sumas de verificación. Para cuando quieras elegir.",
beta="Concat está en **beta**: funciona, y aún tiene aristas. [Cuéntalo](https://github.com/jub0t/Concat/issues) cuando encuentres una.",
platforms="Plataformas",
win="x86_64 y ARM. Un instalador y un `.msi`. Si SmartScreen detiene una compilación sin firmar: **Más información** › **Ejecutar de todas formas**",
mac="Intel y Apple Silicon. Si macOS se niega a abrir una compilación sin firmar: `xattr -dr com.apple.quarantine /Applications/Concat.app`",
linux="x86_64 y ARM. `.deb`, `.rpm`, `.AppImage` y un paquete para Arch. También un Flatpak en **[Flatpark](https://flatpark.org/apps/app.concat.editor/)**, un remoto Flatpak comunitario que envuelve el `.deb` x86_64 de cada versión y se actualiza con ella",
android="teléfonos y tabletas", ios="iPhone y iPad, por sideload",
legend="✅ Compatible · 🚧 En desarrollo · 🧪 Por probar",
sysreq="Los **requisitos del sistema** y los tamaños de los modelos opcionales están en [el sitio web](https://concatenate.pages.dev/guides/system-requirements).",
start_h="Primeros pasos", start1="Descárgalo, ábrelo, suelta el material, corta. Sin cuenta, sin configuración.",
reporting="Para informar de algo:", reporting_text="cada ejecución escribe un registro, y en Ajustes › Acerca de está el botón que lo abre junto al que copia la información de tu sistema. Adjunta ambos a un [issue](https://github.com/jub0t/Concat/issues) y el informe llega con todo lo que necesita. Se conservan las últimas diez ejecuciones, así que la de ayer sigue ahí; nada se envía nunca a ningún sitio por sí solo.",
contribute_h="Cómo contribuir",
contrib1="La mejor forma de contribuir es coger una compilación de la página de [Releases](https://github.com/jub0t/Concat/releases) y usarla: encuentra dónde falla y di dónde podría ser mejor.",
contrib2="¿Listo para escribir código? [CONTRIBUTING.md](../CONTRIBUTING.md) cubre la configuración, la disposición del árbol, las comprobaciones que ejecutar y cómo se licencian las contribuciones. ¿Controlas Concat desde un script, un servicio o un agente? [La documentación para desarrolladores](https://concatenate.pages.dev/docs) cubre la API de Concat y sus transportes: JSON-RPC, gRPC y MCP. [Esta Discussion](https://github.com/jub0t/Concat/discussions/3) es donde se anunció el proyecto.",
contrib3="Los colaboradores pueden reclamar un rol `@Contributor` en el servidor de Discord, solo hay que pedirlo.",
contributors_h="Colaboradores", stars_h="Historial de estrellas",
sponsoring_h="Patrocinio",
sponsoring1="Concat no tiene muro de pago y nunca lo tendrá: sin marca de agua, sin cuenta, sin nivel de pago. El patrocinio es lo que ocupa su lugar. Si Concat ha sustituido una suscripción para ti, una fracción de ella lo mantiene en marcha.",
where_h="A dónde va", where_text="La [hoja de ruta](https://concatenate.pages.dev/roadmap) expone lo que paga el patrocinio y lo que cuesta cada pieza.",
payment_text='Elige un nivel en [el sitio web](https://concatenate.pages.dev/#sponsor).',
closing="¿No puedes aportar ahora? Una estrella, un informe de error o una mención a alguien que edite vídeo también cuentan mucho.",
)
